### ISSUE TITLE
otelcol coredumps on startup in 0.68.1

### ISSUE THREAD

**Issue by govardha** [signalfx/splunk-otel-collector#2465]
I have been tweaking my setup both in the agents & clusterreceiver and although I am using the helm chart, I upgraded the image to 0.68.1.  On startup, just the cluster receiver is core dumping.  The agents are starting up fine.  I am reasonably sure I have something funky in my setup, but that should still not cause a core dump.

Here are the details.

```
2023/01/12 18:48:00 settings.go:310: Set config to [/conf/relay.yaml]
2023/01/12 18:48:00 settings.go:363: Set ballast to 165 MiB
2023/01/12 18:48:00 settings.go:379: Set memory limit to 450 MiB
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x3e7a335]

goroutine 1 [running]:
github.com/signalfx/splunk-otel-collector/internal/configconverter.RenameK8sTagger.Convert({}, {0xc00120e390?, 0xc00120e360?}, 0xc000681f60)
        github.com/signalfx/splunk-otel-collector/internal/configconverter/k8s_tagger.go:56 +0x3d5
go.opentelemetry.io/collector/confmap.(*Resolver).Resolve(0xc001301b60, {0x5ce3f70, 0xc000076030})
        go.opentelemetry.io/collector/confmap@v0.68.1-0.20221221114823-4cf50d0f0d9d/resolver.go:178 +0x28e
go.opentelemetry.io/collector/otelcol.(*configProvider).Get(0x5cab2e0?, {0x5ce3f70?, 0xc000076030?}, {0xc00049fad0?, 0xc000599ce0?, 0xc000598ff0?, 0xc000be1ef0?})
        go.opentelemetry.io/collector@v0.68.1-0.20221221114823-4cf50d0f0d9d/otelcol/configprovider.go:91 +0x72
go.opentelemetry.io/collector/otelcol.(*Collector).setupConfigurationComponents(0xc00129f788, {0x5ce3f70, 0xc000076030})
        go.opentelemetry.io/collector@v0.68.1-0.20221221114823-4cf50d0f0d9d/otelcol/collector.go:154 +0x6f
go.opentelemetry.io/collector/otelcol.(*Collector).Run(0xc00129f788, {0x5ce3f70, 0xc000076030})
        go.opentelemetry.io/collector@v0.68.1-0.20221221114823-4cf50d0f0d9d/otelcol/collector.go:205 +0x65
go.opentelemetry.io/collector/otelcol.NewCommand.func1(0xc000191200, {0x52323de?, 0x0?, 0x1?})
        go.opentelemetry.io/collector@v0.68.1-0.20221221114823-4cf50d0f0d9d/otelcol/command.go:53 +0x419
github.com/spf13/cobra.(*Command).execute(0xc000191200, {0xc000072050, 0x0, 0x1})
        github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000191200)
        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.1/command.go:968
main.runInteractive({{0xc00049fad0, 0xc000599ce0, 0xc000598ff0, 0xc000be1ef0}, {{0x52319c0, 0x7}, {0x0, 0x0}, {0x5c890a0, 0x7}}, ...})
        github.com/signalfx/splunk-otel-collector/cmd/otelcol/main.go:118 +0x5d
main.run(...)
        github.com/signalfx/splunk-otel-collector/cmd/otelcol/main_others.go:26
main.main()
        github.com/signalfx/splunk-otel-collector/cmd/otelcol/main.go:111 +0x1498

```

**Comment by rmfitzpatrick** [comment]
@govardha thanks for reporting this issue. Depending on your config specifying `--no-convert-config` to the collector service would be a workaround. Would you be able to share your redacted cluster receiver config so that we can potentially better resolve the issue?

**Comment by govardha** [comment]
Sure thing.  Here's the ConfigMap from the clusterreceiver.

[ClusterReceiver-CM-Broken.zip](https://github.com/signalfx/splunk-otel-collector/files/10405390/ClusterReceiver-CM-Broken.zip)

**Comment by atoulme** [comment]
From @jamie1911:
>  im not sure this is fully fixed. I still can't start any containers that have 0.69.0.
>
>   line: panic: runtime error: invalid memory address or nil pointer dereference
>   source: stderr
>   tag: splunk-otel-collector/081389b4048d

@jamie1911 please send the whole error message including the stacktrace so we can see where the panic originates, it may be later in the code. I'll reopen https://github.com/signalfx/splunk-otel-collector/issues/2465 with your comment.

Please provide reproduction steps as well if possible.

**Comment by jamie1911** [comment]
There is not a whole lot to reproduce. the ECS task has the following container definition as listed here:https://docs.splunk.com/Observability/gdi/opentelemetry/deployments/deployments-fargate.html#getting-started

The ECS task starts up, however when it tries to start the splunk_otel_collector container, it exits with code: 2 and then AWS recycles the entire task.

changing: `"image": "quay.io/signalfx/splunk-otel-collector:latest"`, to `"image": "quay.io/signalfx/splunk-otel-collector:0.64.0"` allows the ECS task to start as expected.

after enabling logging on the splunk_otel_collector, I can see inside our splunk enterprise the following:
```

{"line":"\[tgithub.com/signalfx/signalfx-agent@v1.0.1-0.20230117211433-9858481024e4/pkg/utils/time.go:46](https://tgithub.com/signalfx/signalfx-agent@v1.0.1-0.20230117211433-9858481024e4/pkg/utils/time.go:46) +0xb8","source":"stderr","tag":"splunk-otel-collector/633f510a267d"}
{"line":"created by [github.com/signalfx/signalfx-agent/pkg/utils.RunOnInterval](https://github.com/signalfx/signalfx-agent/pkg/utils.RunOnInterval)","source":"stderr","tag":"splunk-otel-collector/633f510a267d"}
{"line":"\[tgithub.com/signalfx/signalfx-agent@v1.0.1-0.20230117211433-9858481024e4/pkg/utils/time.go:47](https://tgithub.com/signalfx/signalfx-agent@v1.0.1-0.20230117211433-9858481024e4/pkg/utils/time.go:47) +0x63","source":"stderr","tag":"splunk-otel-collector/633f510a267d"}
{"line":"[github.com/signalfx/signalfx-agent/pkg/utils.RunOnInterval.func1()](https://github.com/signalfx/signalfx-agent/pkg/utils.RunOnInterval.func1())","source":"stderr","tag":"splunk-otel-collector/633f510a267d"}
{"line":"\[tgithub.com/signalfx/signalfx-agent@v1.0.1-0.20230117211433-9858481024e4/pkg/monitors/ecs/ecs.go:111](https://tgithub.com/signalfx/signalfx-agent@v1.0.1-0.20230117211433-9858481024e4/pkg/monitors/ecs/ecs.go:111) +0x32b","source":"stderr","tag":"splunk-otel-collector/633f510a267d"}
{"line":"[github.com/signalfx/signalfx-agent/pkg/monitors](https://github.com/signalfx/signalfx-agent/pkg/monitors)/ecs.(*Monitor).Configure.func1()","source":"stderr","tag":"splunk-otel-collector/633f510a267d"}
{"line":"\[tgithub.com/signalfx/signalfx-agent@v1.0.1-0.20230117211433-9858481024e4/pkg/monitors/ecs/ecs.go:211](https://tgithub.com/signalfx/signalfx-agent@v1.0.1-0.20230117211433-9858481024e4/pkg/monitors/ecs/ecs.go:211) +0x9c8","source":"stderr","tag":"splunk-otel-collector/633f510a267d"}
{"line":"[github.com/signalfx/signalfx-agent/pkg/monitors](https://github.com/signalfx/signalfx-agent/pkg/monitors)/ecs.(*Monitor).fetchStatsForAll(0xc0009cac00, {0x42?, 0x0?, 0x0?, 0x0?})","source":"stderr","tag":"splunk-otel-collector/633f510a267d"}
{"line":"\[tgithub.com/signalfx/splunk-otel-collector/receiver/smartagentreceiver@v0.0.0-00010101000000-000000000000/output.go:275](https://tgithub.com/signalfx/splunk-otel-collector/receiver/smartagentreceiver@v0.0.0-00010101000000-000000000000/output.go:275) +0x46d","source":"stderr","tag":"splunk-otel-collector/633f510a267d"}
{"line":"[github.com/signalfx/splunk-otel-collector/receiver](https://github.com/signalfx/splunk-otel-collector/receiver)/smartagentreceiver.(*output).SendDimensionUpdate(0xc000f4bf40, 0xc0014155c0)","source":"stderr","tag":"splunk-otel-collector/633f510a267d"}
{"line":"\[tgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxexporter@v0.69.0/exporter.go:61](https://tgithub.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxexporter@v0.69.0/exporter.go:61) +0x1d","source":"stderr","tag":"splunk-otel-collector/633f510a267d"}
{"line":"[github.com/open-telemetry/opentelemetry-collector-contrib/exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/exporter)/signalfxexporter.(*signalfMetadataExporter).ConsumeMetadata(0xc000d7b4a8?, {0xc0000126f8?, 0x523ea66?, 0xc?})","source":"stderr","tag":"splunk-otel-collector/633f510a267d"}
{"line":"goroutine 144 [running]:","source":"stderr","tag":"splunk-otel-collector/633f510a267d"}
{"line":"","source":"stderr","tag":"splunk-otel-collector/633f510a267d"}
{"line":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10a595d]","source":"stderr","tag":"splunk-otel-collector/633f510a267d"}
{"line":"panic: runtime error: invalid memory address or nil pointer dereference","source":"stderr","tag":"splunk-otel-collector/633f510a267d"}
{"line":"2023-01-23T20:14:01.610Z\tinfo\tservice/pipelines.go:109\tReceiver started.\t{\"kind\": \"receiver\", \"name\": \"smartagent/ecs-metadata\", \"pipeline\": \"metrics\"}","source":"stderr","tag":"splunk-otel-collector/633f510a267d"}


```

**Comment by atoulme** [comment]
Your stacktrace is very different from the original report. Looking at the code associated.

**Comment by atoulme** [comment]
Closing as the work continues with #2508.
